import json
import requests, pyotp
from behave import *
from app.fake_providers import fake

REQUEST_HEADERS = {"accept": "application/json"}
AUTH_HEADER = "Authorization"
AUTH_PREFIX = "Bearer "


@given("set request token from global param '{global_param}'")
def step_impl(context, global_param):
    """Set the auth header using a token from a global parameter."""
    auth_header = AUTH_PREFIX + context.global_params[global_param]
    context.request_headers[AUTH_HEADER] = auth_header


@given("set request token from response param '{response_param}'")
def step_impl(context, response_param):
    """Set the auth header using a token from a response parameter."""
    auth_header = AUTH_PREFIX + context.response_params[response_param]
    context.request_headers[AUTH_HEADER] = auth_header


@given("set request placeholder '{request_placeholder}' from global param '{global_param}'")
def step_impl(context, request_placeholder, global_param):
    """Set a request placeholder using a global parameter."""
    param = context.global_params[global_param]
    context.request_placeholders[request_placeholder] = param


@given("set request param '{request_param}' from value '{value}'")
def step_impl(context, request_param, value):
    """Set a request parameter to a value or handle special cases."""
    if value == "none":
        if request_param in context.request_params:
            del context.request_params[request_param]

    elif value == "empty":
        context.request_params[request_param] = ""

    elif value == "spaces":
        context.request_params[request_param] = " " * 8

    elif value == "tabs":
        context.request_params[request_param] = "   " * 8

    else:
        context.request_params[request_param] = value


@given("set request param '{request_param}' from fake '{fake_provider}'")
def step_impl(context, request_param, fake_provider):
    """Set a request parameter generated by a Faker provider."""
    context.request_params[request_param] = getattr(fake, fake_provider)()


@given("set request param '{request_param}' from config param '{config_param}'")
def step_impl(context, request_param, config_param):
    """Set a request parameter from a configuration parameter."""
    context.request_params[request_param] = context.config_params[config_param]


@given("generate request param 'user_totp' from config param '{config_param}'")
def step_impl(context, config_param):
    """Generate a user_totp request parameter using."""
    mfa_key = context.config_params[config_param]
    context.request_params["user_totp"] = pyotp.TOTP(mfa_key).now()


@then("delete global param '{global_param}'")
def step_impl(context, global_param):
    """Remove a global parameter from the context."""
    if global_param in context.global_params:
        del context.global_params[global_param]


@when("send '{request_method}' request to url '{request_url}'")
def step_impl(context, request_method, request_url):
    """Send an HTTP request with the specified method."""
    for placeholder in context.request_placeholders:
        request_url = request_url.replace(":" + placeholder, str(context.request_placeholders[placeholder]))
    url = context.config_params["base_url"] + request_url
    headers = context.request_headers
    headers["accept"] = "application/json"
    params = context.request_params

    if request_method == "POST":
        response = requests.post(url, headers=headers, params=params, files=context.request_files)

    elif request_method == "GET":
        response = requests.get(url, headers=headers, params=params)

    elif request_method == "PUT":
        response = requests.put(url, headers=headers, params=params)

    elif request_method == "DELETE":
        response = requests.delete(url, headers=headers, params=params)

    context.response_code = response.status_code
    context.response_params = json.loads(response.text)

    context.request_headers = {}
    context.request_params = {}
